# Terminal & Color Settings
set -g default-terminal "tmux-256color"
set -g allow-passthrough on
set -as terminal-overrides ',xterm-ghostty:Ss=\E[%p1%d q:Se=\E[2q'
set -as terminal-overrides ',xterm*:Ss=\E[%p1%d q:Se=\E[2q'


set -g @vi_mode "#[fg=green,bold][INSERT]#[default]"
set -g status-right "#{@vi_mode} %H:%M"

# Copy-mode & Keybindings
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key e new-window "~/.local/scripts/tmux-sessionizer"

set -g -u SSH_CLIENT
set -g -u SSH_CONNECTION
set -g -u SSH_TTY

set -g update-environment "DISPLAY WAYLAND_DISPLAY XAUTHORITY SSH_AUTH_SOCK"
